In [1]:
%pip install xlrd

Collecting xlrd
  Downloading xlrd-2.0.2-py2.py3-none-any.whl.metadata (3.5 kB)
Downloading xlrd-2.0.2-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.2
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

raw = pd.read_excel(
    "../data/raw/cepea_arabica_daily.xls",
    engine="xlrd",
    skiprows=3,
    engine_kwargs={"ignore_workbook_corruption": True},
)
raw.head()

         Data À vista R$ À vista US$
0  04/01/2016     496,87      122,74
1  05/01/2016     504,26      126,32
2  06/01/2016     497,49      123,81
3  07/01/2016     496,31      122,73
4  08/01/2016     502,60      124,59

In [4]:
raw.dtypes

Data           str
À vista R$     str
À vista US$    str
dtype: object

In [5]:
df = raw.copy()
df.columns = ["date", "price_brl_bag", "price_usd_bag"]

df["date"] = pd.to_datetime(df["date"], format="%d/%m/%Y")

for col in ["price_brl_bag", "price_usd_bag"]:
    df[col] = (
        df[col]
        .str.replace(".", "", regex=False)
        .str.replace(",", ".", regex=False)
        .astype(float)
    )

df.info()
df.tail()

<class 'pandas.DataFrame'>
RangeIndex: 2698 entries, 0 to 2697
Data columns (total 3 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   date           2698 non-null   datetime64[us]
 1   price_brl_bag  2698 non-null   float64
 2   price_usd_bag  2698 non-null   float64
dtypes: datetime64[us](1), float64(2)
memory usage: 63.4 KB

           date  price_brl_bag  price_usd_bag
2693 2026-10-20        1610.14         320.68
2694 2026-10-21        1620.92         322.38
2695 2026-10-22        1619.85         321.72
2696 2026-10-23        1601.95         320.90
2697 2026-10-26        1627.46         301.77

In [6]:
"1.610,14".replace(",", ".").replace(".", "")

'161014'

In [7]:
df.to_csv("../data/processed/cepea_arabica_daily_clean.csv", index=False)